skillMetadata:
  sections:
    - name: Bring! login
      fields:
        - name: email
          type: email
          label: Email
          value: ''
        - name: password
          type: password
          label: Password
          value: ''
    - name: Default shopping list
      fields:
        - type: label
          label: This is the shopping list that will be set everytime you restart Mycroft. The name is case-sensitive.
        - name: default_list
          type: text
          label: Name of your default shopping list
          value: ''
