skillMetadata:
  sections:
    - name: Bring! login
      fields:
        - name: email
          type: email
          label: Email
          value: ''
        - name: password
          type: password
          label: Password
          value: ''
    - name: Default shopping list
      fields:
        - type: label
          label: The name of the shopping list to be used when no list is explicitly specified and none was set using Mycroft. Be sure to type in the exact name of the list in Bring!.
        - name: active_list
          type: text
          label: Name of your default shopping list
          value: ''
